config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks, only: [:create, :destroy]
  end
  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks, dependent: :destroy
    validates :name, presence: true
end
  

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :name, presence: true
  validates :description, length: { maximum: 500 }, allow_blank: true

  before_save :set_due_date_to_today_if_past

  private

  def set_due_date_to_today_if_past
    if due_date.present? && due_date < Date.today
      self.due_date = Date.today  # Define a data de validade como o dia atual
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.includes(:tasks).all  # Isso carrega todas as listas e suas tarefas associadas
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path, notice: 'Lista criada com sucesso!'
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: 'Lista removida com sucesso!'
  end  

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.build(task_params)

    if @task.name.blank?  # Verifica se o nome está vazio
      redirect_to list_path(@list)  # Redireciona de volta para a lista sem fazer nada
    elsif @task.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to list_path(@task.list)
  end

  private

  def task_params
    params.require(:task).permit(:name, :completed, :description, :due_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todolist" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application" %>
    <head>
      <title>Todolist</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
      <%= stylesheet_link_tag 'custom', media: 'all' %> <!-- Adicionamos aqui -->
    </head>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="header">
  <div class="header-logo">
    <img src="<%= asset_path('logov360.png') %>" alt="Logo V360" class="v360-logo">
  </div>
  <div class="header-title">
    <h1>TO DO LIST</h1>
  </div>
</div>
<div class="page-container">
  <h1 class="page-title">MINHAS LISTAS</h1>

  <!-- Botão para criar uma nova lista -->
  <div class="button-container">
    <%= link_to 'Nova Lista', new_list_path, class: 'btn btn-new-list' %>
  </div>

  <!-- Contêiner de cartões das listas -->
  <div class="cards-container">
    <% @lists.each do |list| %>
      <div class="card">
        <!-- Nome da lista -->
        <h2 class="card-title"><%= list.name %></h2>

        <!-- Tarefas da lista -->
        <ul class="task-list">
          <% list.tasks.each do |task| %>
            <li class="task-item">
              <h3 class="task-name"><%= task.name %></h3>
              <!-- Exibe a descrição da tarefa, ou uma mensagem caso não tenha descrição -->
              <!-- <p class="task-description"><%= task.description.present? ? task.description : "Sem descrição" %></p> -->
              <p><strong></strong> <%= task.due_date %></p>
              <!-- <%= button_to 'Remover Tarefa', list_task_path(list, task), method: :delete, class: 'btn btn-delete' %> -->
            </li>
          <% end %>
        </ul>

        <!-- Formulário para adicionar tarefas -->
        <%= form_with model: [list, Task.new], local: true, html: { class: 'task-form' } do |form| %>
          <div class="form-group">
            <%= form.hidden_field :name, placeholder: 'Nova Tarefa', class: 'form-input' %>
            <%= form.submit 'Editar Lista', class: 'btn btn-add-task' %>
          </div>
        <% end %>

        <!-- Botão para remover a lista -->
        <%= button_to 'Remover Lista', list_path(list), method: :delete, data: { confirm: 'Você tem certeza que deseja remover esta lista?' }, class: 'btn btn-delete-list' %>
      </div>
    <% end %>
  </div>
  <!--
  <div class="logo-container">
    <img src="<%= asset_path('logov360.png') %>" alt="Logo V360" class="v360-logo">
  </div> 
  -->
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1 class="title">Criar Nova Lista</h1>

  <%= form_with model: @list, local: true, class: "form" do |form| %>
    <div class="form-group">
      <%= form.label :name, "Nome da Lista", class: "form-label" %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div class="form-actions">
      <%= form.submit 'Criar Lista', class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to 'Voltar', lists_path, class: "btn btn-secondary" %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1 class="title"><%= @list.name %></h1>

  <!-- Formulário para adicionar novas tarefas -->
  <%= form_with model: [@list, Task.new], local: true, html: { class: 'task-form' } do |form| %>
    <div class="form-group">
      <%= form.label :name, 'Nova Tarefa', class: 'form-label' %>
      <%= form.text_field :name, class: 'form-input' %>
    </div>
    <div class="form-group">
      <%= form.label :description, 'Descrição', class: 'form-label' %>
      <%= form.text_area :description, class: 'form-input' %>
    </div>
    <div class="form-group">
      <%= form.label :due_date, 'Data de Validade', class: 'form-label' %>
      <%= form.date_field :due_date, class: 'form-input' %>
    </div>
    <div>
      <%= form.submit 'Adicionar Tarefa', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <!-- Lista de tarefas -->
  <ul class="task-list">
    <% @tasks.each do |task| %>
      <li class="task-item">
        <p><strong>Título: <%= task.name %></strong></p>
        <p><strong>Descrição:</strong> <%= task.description.present? ? task.description : "Sem descrição" %></p>
        <p><strong>Prazo:</strong> <%= task.due_date.present? ? task.due_date.strftime('%d/%m/%Y') : "Sem data de validade" %></p>
        <%= button_to 'Remover', list_task_path(@list, task), method: :delete, class: 'btn btn-delete' %>
      </li>
    <% end %>
  </ul>

  <!-- Link para voltar -->
  <div class="link-container">
    <%= link_to 'Voltar', lists_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>